site_name: doc2dict

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - content.code.copy

nav:
  - Home: index.md
  - doc2dict:
    - html: parsing/html.md
    - pdf: parsing/pdf.md
  - White Paper: whitepaper.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - def_list
  - admonition
  - pymdownx.details
  - toc:
      permalink: true

repo_url: https://github.com/john-friedman/doc2dict
repo_name: john-friedman/doc2dict