name: Deploy MkDocs

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions
      
      - name: Build and deploy MkDocs
        run: |
          # Navigate to the docs directory
          cd doc2dict/docs
          
          # Build the site
          mkdocs build
          
          # Deploy to GitHub Pages
          mkdocs gh-deploy --force